arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/l10n
output-localization-file: app_localizations.dart
synthetic-package: false
use-escaping: true
untranslated-messages-file: l10n_missing.json
