import 'package:financial_literacy_game/presentation/screens/home_page.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'firebase_options.dart'; // generated by flutterfire configure
import 'package:firebase_core/firebase_core.dart';

import 'config/constants.dart';
import 'config/themes.dart';
import 'domain/game_data_notifier.dart';

// Generated localization (flutter gen-l10n output)
import 'l10n/app_localizations.dart';
import 'l10n/l10n.dart';
import 'l10n/fallback_localizations.dart';

// Optional: your custom Luganda material localizations
// import 'l10n/lg_intl.dart'; // <-- only if this file exists and compiles

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final locale = ref.watch(gameDataNotifierProvider).locale;

    return MaterialApp(
      localeResolutionCallback: (l, s) => l ?? const Locale('en'),
      debugShowCheckedModeBanner: false,
      title: appTitle,
      themeMode: ThemeMode.system,
      theme: lightTheme,
      darkTheme: darkTheme,

      // Current locale chosen by the user (via your dropdown in the UI)
      locale: locale,

      // Localizations
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        FallbackMaterialLocalizations.delegate,
        FallbackWidgetsLocalizations.delegate,
        FallbackCupertinoLocalizations.delegate,
      ],
      supportedLocales: L10n.all,                 // list of supported locales

      // Your first screen (put the language dropdown in its AppBar/actions)
      home: const Homepage(),
    );
  }
}
